[Settings]
# 模板文件路径；默认值: config/demo.txt | Template file path; Default value: config/demo.txt
source_file = config/user_demo.txt
# 生成结果文件路径；默认值: output/result.txt | Generate result file path; Default value: output/result.txt
final_file = output/user_result.txt
local_file = config/user_local.txt
alias_file = config/user_alias.txt
whitelist_file = config/user_whitelist.txt
subscribe_file = config/user_subscribe.txt

max_resolution = 3840x2160

# 开启使用历史更新结果（包含模板与结果文件的接口），合并至本次更新中；可选值: True, False | Enable to use historical update results (including interfaces of templates and result files), merged into this update; Optional values: True, False
open_history = False