[Settings]
# 模板文件路径；默认值: config/demo.txt | Template file path; Default value: config/demo.txt
source_file = config/user_demo.txt
# 生成结果文件路径；默认值: output/result.txt | Generate result file path; Default value: output/result.txt
final_file = output/user_result.txt
local_file = config/user_local.txt
alias_file = config/user_alias.txt
whitelist_file = config/user_whitelist.txt
subscribe_file = config/user_subscribe.txt

max_resolution = 3840x2160

# 开启使用历史更新结果（包含模板与结果文件的接口），合并至本次更新中；可选值: True, False | Enable to use historical update results (including interfaces of templates and result files), merged into this update; Optional values: True, False
open_history = False

; =========================
; 定时执行设置 / Scheduled Execution Settings
; =========================

# 定时执行更新时间模式，不作用于工作流；可选值: interval、time； interval: 按间隔时间执行，time: 按指定时间点执行 | Scheduled execution update mode, does not apply to workflow; Optional values: interval, time; interval: execute by interval time, time: execute at specified time point
update_mode = interval
# 定时执行更新时间间隔，仅在update_mode = interval时生效，单位小时，设置 0 或空则只运行一次；默认值: 12 | Scheduled execution update interval, only takes effect when update_mode = interval, unit hours, set to 0 or empty to run only once; Default value: 12
update_interval = 48
# 定时执行更新时间点，仅在update_mode = time时生效，格式 HH:MM，支持多个时间点逗号分隔 | Scheduled execution update time point, only takes effect when update_mode = time, format HH:MM, supports multiple time points separated by commas
update_times =
# 启动时执行更新，用于控制程序启动后是否立即执行一次更新；可选值: True, False | Execute update at startup, used to control whether to execute an update immediately after the program starts; Optional values: True, False
update_startup = True
# 时区，可用于控制定时执行时区或显示更新时间的时区；可选值: Asia/Shanghai 或其它时区编码 | Time zone, can be used to control the time zone for scheduled execution or display update time; Optional values: Asia/Shanghai or other time zone codes
time_zone = Asia/Shanghai